Update for cleaner os/x builds.
git-svn-id: svn+ssh://svn.code.sf.net/p/lemur/code/indri/trunk@907 14020d50-3050-45fe-8e0c-5ed7005ca764

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AR SHARED INDRI_STANDALONE JAVAC JAR JAVAINC JAVAHOME WITH_JAVA PHPCONFIG PHPINCLUDE WITH_PHP MCS SWIG CXXCPP EGREP NEED_ANTLR WITH_CSHARP WITH_SWIG PHP_SHARED JAVA_SHARED CSHARP_SHARED PHP_SO JAVA_SO CSHARP_SO SITESEED LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA AR GCC_33 SHARED INDRI_STANDALONE JAVAC JAR JAVADOC JAVAINC WITH_JAVA PHPCONFIG PHPINCLUDE WITH_PHP MCS SWIG CXXCPP EGREP NEED_ANTLR WITH_CSHARP WITH_SWIG PHP_SHARED JAVA_SHARED CSHARP_SHARED PHP_SO JAVA_SO CSHARP_SO SITESEED LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3105,6 +3105,45 @@ echo "$as_me: error: cannot find the program ar on your path. Add AR=/path/to/ar
    { (exit 1); exit 1; }; }
 fi
 
+echo "$as_me:$LINENO: checking for a supported version of gcc" >&5
+echo $ECHO_N "checking for a supported version of gcc... $ECHO_C" >&6
+
+gcc_version=`${CC} -dumpversion`
+GCC_33=0
+case "${gcc_version}" in
+     2.*)
+	echo "$as_me:$LINENO: result: no (${gcc_version})" >&5
+echo "${ECHO_T}no (${gcc_version})" >&6
+	{ { echo "$as_me:$LINENO: error: please use a recent (>= gcc-3.2) version of gcc" >&5
+echo "$as_me: error: please use a recent (>= gcc-3.2) version of gcc" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+     3.0*)
+	echo "$as_me:$LINENO: result: no (${gcc_version})" >&5
+echo "${ECHO_T}no (${gcc_version})" >&6
+	{ { echo "$as_me:$LINENO: error: please use a recent (>= gcc-3.2) version of gcc" >&5
+echo "$as_me: error: please use a recent (>= gcc-3.2) version of gcc" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+     3.1*)
+	echo "$as_me:$LINENO: result: no (${gcc_version})" >&5
+echo "${ECHO_T}no (${gcc_version})" >&6
+	{ { echo "$as_me:$LINENO: error: please use a recent (>= gcc-3.2) version of gcc" >&5
+echo "$as_me: error: please use a recent (>= gcc-3.2) version of gcc" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+     3.3*)
+	echo "$as_me:$LINENO: result: buggy (${gcc_version})" >&5
+echo "${ECHO_T}buggy (${gcc_version})" >&6
+        GCC_33=1
+	;;
+     *)
+	echo "$as_me:$LINENO: result: ok (${gcc_version})" >&5
+echo "${ECHO_T}ok (${gcc_version})" >&6
+	;;
+esac
+
+
 INDRI_STANDALONE=1
 
 cat >>confdefs.h <<\_ACEOF
@@ -4972,7 +5011,7 @@ if test "$enable_java" = "yes" ; then
 # Check whether --with-javahome or --without-javahome was given.
 if test "${with_javahome+set}" = set; then
   withval="$with_javahome"
-  JAVAHOME="$withval"; JAVACBIN=$JAVAHOME/bin/javac; JAVAINCDIR=$JAVAHOME/include; JAR=$JAVAHOME/bin/jar
+  JAVAHOME="$withval"; JAVACBIN=$JAVAHOME/bin/javac; JAVAINCDIR=$JAVAHOME/include; JAR=$JAVAHOME/bin/jar; JAVADOC=$JAVAHOME/bin/javadoc
 else
   JAVAHOME=
 fi;
@@ -5064,6 +5103,50 @@ echo "${ECHO_T}no" >&6
 fi
 
   test -n "$JAR" && break
+done
+
+     for ac_prog in javadoc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVADOC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVADOC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVADOC="$JAVADOC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAVADOC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAVADOC=$ac_cv_path_JAVADOC
+
+if test -n "$JAVADOC"; then
+  echo "$as_me:$LINENO: result: $JAVADOC" >&5
+echo "${ECHO_T}$JAVADOC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$JAVADOC" && break
 done
 
    else
@@ -6627,12 +6710,13 @@ s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
 s,@AR@,$AR,;t t
+s,@GCC_33@,$GCC_33,;t t
 s,@SHARED@,$SHARED,;t t
 s,@INDRI_STANDALONE@,$INDRI_STANDALONE,;t t
 s,@JAVAC@,$JAVAC,;t t
 s,@JAR@,$JAR,;t t
+s,@JAVADOC@,$JAVADOC,;t t
 s,@JAVAINC@,$JAVAINC,;t t
-s,@JAVAHOME@,$JAVAHOME,;t t
 s,@WITH_JAVA@,$WITH_JAVA,;t t
 s,@PHPCONFIG@,$PHPCONFIG,;t t
 s,@PHPINCLUDE@,$PHPINCLUDE,;t t
